# PiTrac Advanced Configuration
# This file contains advanced tuning parameters for PiTrac.
# Edit these values using: pitrac config edit --advanced
#
# WARNING: These settings can significantly affect ball detection accuracy.
# Only modify if you understand the implications.
#
# All basic settings are also available here.

version: 2.0
profile: advanced

# ============================================================================
# INCLUDES BASIC SETTINGS (see settings-basic.yaml)
# ============================================================================
_includes: settings-basic.yaml

# ============================================================================
# HOUGH CIRCLES BALL DETECTION (LEGACY MODE)
# ============================================================================

ball_detection_advanced:
  # Canny edge detection thresholds for strobed balls
  strobed_balls:
    # Lower threshold for Canny edge detection
    # Range: 0-255
    # Default: 33
    # Maps to: gs_config.ball_identification.kStrobedBallsCannyLower
    canny_lower: 33
    
    # Upper threshold for Canny edge detection
    # Range: 0-255 (should be 2-3x lower threshold)
    # Default: 90
    # Maps to: gs_config.ball_identification.kStrobedBallsCannyUpper
    canny_upper: 90
    
    # Minimum circles to return
    # Range: 1-50
    # Default: 6
    # Maps to: gs_config.ball_identification.kStrobedBallsMinHoughReturnCircles
    min_circles: 6
    
    # Maximum circles to return
    # Range: 1-100
    # Default: 20
    # Maps to: gs_config.ball_identification.kStrobedBallsMaxHoughReturnCircles
    max_circles: 20
    
    # HoughCircles Param2 range (accumulator threshold)
    # Lower values = more circles detected
    param2:
      # Range: 1-200
      # Default: 18
      # Maps to: gs_config.ball_identification.kStrobedBallsMinParam2
      min: 18
      
      # Range: 1-300
      # Default: 140
      # Maps to: gs_config.ball_identification.kStrobedBallsMaxParam2
      max: 140
      
      # Range: between min and max
      # Default: 60
      # Maps to: gs_config.ball_identification.kStrobedBallsStartingParam2
      starting: 60
      
      # Range: 0.1-20
      # Default: 4
      # Maps to: gs_config.ball_identification.kStrobedBallsParam2Increment
      increment: 4
    
    # HoughCircles Param1 (higher threshold for center detection)
    # Range: 1-500
    # Default: 130
    # Maps to: gs_config.ball_identification.kStrobedBallsCurrentParam1
    param1: 130
    
    # Inverse accumulator resolution ratio
    # Range: 1.0-3.0
    # Default: 1.7
    # Maps to: gs_config.ball_identification.kStrobedBallsHoughDpParam1
    dp: 1.7
    
    # Gaussian blur kernel sizes (must be odd)
    # Pre-Canny blur
    # Options: 1, 3, 5, 7, 9
    # Default: 3
    # Maps to: gs_config.ball_identification.kStrobedBallsPreCannyBlurSize
    pre_canny_blur: 3
    
    # Pre-Hough blur
    # Options: 1, 3, 5, 7, 9, 11, 13, 15
    # Default: 13
    # Maps to: gs_config.ball_identification.kStrobedBallsPreHoughBlurSize
    pre_hough_blur: 13
    
  # Alternative algorithm parameters (for different lighting)
  alternative_algorithm:
    # Use alternative HoughCircles parameters
    # Options: true, false
    # Default: true
    # Maps to: gs_config.ball_identification.kStrobedBallsUseAltHoughAlgorithm
    enabled: true
    
    # Alternative Canny thresholds
    # Maps to: gs_config.ball_identification.kStrobedBallsAltCannyLower
    canny_lower: 35
    # Maps to: gs_config.ball_identification.kStrobedBallsAltCannyUpper
    canny_upper: 60
    
    # Alternative blur sizes
    # Maps to: gs_config.ball_identification.kStrobedBallsAltPreCannyBlurSize
    pre_canny_blur: 9
    # Maps to: gs_config.ball_identification.kStrobedBallsAltPreHoughBlurSize
    pre_hough_blur: 15
    
    # Alternative Param2 range
    param2:
      # Maps to: gs_config.ball_identification.kStrobedBallsAltMinParam2
      min: 0.5
      # Maps to: gs_config.ball_identification.kStrobedBallsAltMaxParam2
      max: 1.0
      # Maps to: gs_config.ball_identification.kStrobedBallsAltStartingParam2
      starting: 0.65
      # Maps to: gs_config.ball_identification.kStrobedBallsAltParam2Increment
      increment: 0.05
    
    # Maps to: gs_config.ball_identification.kStrobedBallsAltCurrentParam1
    param1: 130.0
    # Maps to: gs_config.ball_identification.kStrobedBallsAltHoughDpParam1
    dp: 0.8

  # Placed (teed) ball detection parameters
  placed_balls:
    # Maps to: gs_config.ball_identification.kPlacedBallCannyLower
    canny_lower: 35
    # Maps to: gs_config.ball_identification.kPlacedBallCannyUpper
    canny_upper: 80
    
    param2:
      # Maps to: gs_config.ball_identification.kPlacedBallMinParam2
      min: 0.8
      # Maps to: gs_config.ball_identification.kPlacedBallMaxParam2
      max: 1.0
      # Maps to: gs_config.ball_identification.kPlacedBallStartingParam2
      starting: 0.9
      # Maps to: gs_config.ball_identification.kPlacedBallParam2Increment
      increment: 0.03
    
    # Maps to: gs_config.ball_identification.kPlacedBallCurrentParam1
    param1: 130.0
    # Maps to: gs_config.ball_identification.kPlacedPreCannyBlurSize
    pre_canny_blur: 11
    # Maps to: gs_config.ball_identification.kPlacedPreHoughBlurSize
    pre_hough_blur: 13
    # Maps to: gs_config.ball_identification.kPlacedMinHoughReturnCircles
    min_circles: 1
    # Maps to: gs_config.ball_identification.kPlacedMaxHoughReturnCircles
    max_circles: 4

  # Putting mode parameters
  putting_mode:
    param2:
      # Maps to: gs_config.ball_identification.kPuttingBallMinParam2
      min: 0.8
      # Maps to: gs_config.ball_identification.kPuttingBallMaxParam2
      max: 1.0
      # Maps to: gs_config.ball_identification.kPuttingBallStartingParam2
      starting: 0.9
      # Maps to: gs_config.ball_identification.kPuttingBallParam2Increment
      increment: 0.03
    
    # Maps to: gs_config.ball_identification.kPuttingBallCurrentParam1
    param1: 300.0
    # Maps to: gs_config.ball_identification.kPuttingMinHoughReturnCircles
    min_circles: 6
    # Maps to: gs_config.ball_identification.kPuttingMaxHoughReturnCircles
    max_circles: 25
    # Maps to: gs_config.ball_identification.kPuttingHoughDpParam1
    dp: 1.5
    # Maps to: gs_config.ball_identification.kPuttingPreHoughBlurSize
    pre_hough_blur: 9

# ============================================================================
# AI DETECTION PARAMETERS (EXPERIMENTAL MODE)
# ============================================================================

ai_detection:
  # ONNX model path
  # Default: Built-in model
  # Maps to: gs_config.ball_identification.kONNXModelPath
  model_path: "../../Software/GroundTruthAnnotator/experiments/high_performance_300e2/weights/best.onnx"
  
  # Confidence threshold
  # Range: 0.0-1.0
  # Default: 0.5
  # Maps to: gs_config.ball_identification.kONNXConfidenceThreshold
  confidence_threshold: 0.5
  
  # Non-Maximum Suppression threshold
  # Range: 0.0-1.0
  # Default: 0.4
  # Maps to: gs_config.ball_identification.kONNXNMSThreshold
  nms_threshold: 0.4
  
  # Input image size
  # Options: 640, 1280, 1472
  # Default: 1472
  # Maps to: gs_config.ball_identification.kONNXInputSize
  input_size: 1472
  
  # SAHI parameters (for experimental_sahi mode)
  sahi:
    # Maps to: gs_config.ball_identification.kSAHISliceHeight
    slice_height: 320
    # Maps to: gs_config.ball_identification.kSAHISliceWidth
    slice_width: 320
    # Maps to: gs_config.ball_identification.kSAHIOverlapRatio
    overlap_ratio: 0.2

# ============================================================================
# BALL POSITION VALIDATION
# ============================================================================

ball_validation:
  # Radius ratio constraints for moving balls
  moving_ball:
    # Maps to: gs_config.ball_position.kMinMovedBallRadiusRatio
    min_radius_ratio: 0.6
    # Maps to: gs_config.ball_position.kMaxMovedBallRadiusRatio
    max_radius_ratio: 1.5
  
  # General radius constraints
  general:
    # Maps to: gs_config.ball_position.kMinRadiusRatio
    min_radius_ratio: 0.8
    # Maps to: gs_config.ball_position.kMaxRadiusRatio
    max_radius_ratio: 1.7
    # Maps to: gs_config.ball_position.kMinRadiusOffset
    min_radius_offset: 20
    # Maps to: gs_config.ball_position.kMaxRadiusOffset
    max_radius_offset: 20
  
  # Narrowing radius ratios for refinement
  narrowing:
    strobed:
      # Maps to: gs_config.ball_identification.kStrobedNarrowingRadiiMinRatio
      min_ratio: 0.7
      # Maps to: gs_config.ball_identification.kStrobedNarrowingRadiiMaxRatio
      max_ratio: 1.6
    placed:
      # Maps to: gs_config.ball_identification.kPlacedNarrowingRadiiMinRatio
      min_ratio: 0.9
      # Maps to: gs_config.ball_identification.kPlacedNarrowingRadiiMaxRatio
      max_ratio: 1.1

# ============================================================================
# BALL EXPOSURE SELECTION
# ============================================================================

exposure_selection:
  # Number of high-quality balls to retain
  # Range: 1-10
  # Default: 2
  # Maps to: gs_config.ball_exposure_selection.kNumberHighQualityBallsToRetain
  high_quality_balls: 2
  
  # Maximum balls to retain
  # Range: 5-100
  # Default: 30
  # Maps to: gs_config.ball_exposure_selection.kMaxBallsToRetain
  max_balls: 30
  
  # Maximum off-trajectory distance
  # Range: 1-50 pixels
  # Default: 8
  # Maps to: gs_config.ball_exposure_selection.kMaximumOffTrajectoryDistance
  max_trajectory_distance: 8
  
  # Color difference thresholds
  color_difference:
    # Strobed balls relaxed threshold
    # Range: 10000-200000
    # Default: 70000
    # Maps to: gs_config.ball_exposure_selection.kMaxStrobedBallColorDifferenceRelaxed
    strobed_relaxed: 70000
    
    # Strobed balls strict threshold
    # Range: 5000-80000
    # Default: 30000
    # Maps to: gs_config.ball_exposure_selection.kMaxStrobedBallColorDifferenceStrict
    strobed_strict: 30000
    
    # Putting balls relaxed threshold
    # Range: 5000-100000
    # Default: 40000
    # Maps to: gs_config.ball_exposure_selection.kMaxPuttingBallColorDifferenceRelaxed
    putting_relaxed: 40000
  
  # Launch angle filtering
  launch_angles:
    # Maximum quality exposure launch angle
    # Range: 10-90 degrees
    # Default: 35
    # Maps to: gs_config.ball_exposure_selection.kMaxQualityExposureLaunchAngle
    max_angle: 35
    
    # Minimum quality exposure launch angle
    # Range: -20 to 20 degrees
    # Default: -5
    # Maps to: gs_config.ball_exposure_selection.kMinQualityExposureLaunchAngle
    min_angle: -5
    
    # Putting mode angles
    # Maps to: gs_config.ball_exposure_selection.kMaxPuttingQualityExposureLaunchAngle
    putting_max: 8
    # Maps to: gs_config.ball_exposure_selection.kMinPuttingQualityExposureLaunchAngle
    putting_min: -5

# ============================================================================
# SPIN ANALYSIS
# ============================================================================

spin_analysis_advanced:
  # Gabor filter white pixel percentages
  gabor:
    # Maps to: gs_config.spin_analysis.kGaborMaxWhitePercent
    max_white_percent: 45
    # Maps to: gs_config.spin_analysis.kGaborMinWhitePercent
    min_white_percent: 39
  
  # 3D rotation search parameters
  rotation_search:
    # X-axis rotation
    # Maps to: gs_config.spin_analysis.kCoarseXRotationDegreesStart
    x_start: -36
    # Maps to: gs_config.spin_analysis.kCoarseXRotationDegreesEnd
    x_end: 36
    # Maps to: gs_config.spin_analysis.kCoarseXRotationDegreesIncrement
    x_increment: 4
    
    # Y-axis rotation
    # Maps to: gs_config.spin_analysis.kCoarseYRotationDegreesStart
    y_start: -15
    # Maps to: gs_config.spin_analysis.kCoarseYRotationDegreesEnd
    y_end: 15
    # Maps to: gs_config.spin_analysis.kCoarseYRotationDegreesIncrement
    y_increment: 5
    
    # Z-axis rotation (spin axis)
    # Maps to: gs_config.spin_analysis.kCoarseZRotationDegreesStart
    z_start: -10
    # Maps to: gs_config.spin_analysis.kCoarseZRotationDegreesEnd
    z_end: 110
    # Maps to: gs_config.spin_analysis.kCoarseZRotationDegreesIncrement
    z_increment: 4

# ============================================================================
# CAMERA ADVANCED SETTINGS
# ============================================================================

camera_advanced:
  # Camera 1 settings
  camera1:
    # High FPS gain
    # Range: 1.0-32.0
    # Default: 15.0
    # Maps to: gs_config.cameras.kCamera1HighFPSGain
    high_fps_gain: 15.0
    
    # Contrast
    # Range: 0.0-32.0
    # Default: 1.0
    # Maps to: gs_config.cameras.kCamera1Contrast
    contrast: 1.0
    
    # Still image shutter time (microseconds)
    # Range: 100-1000000
    # Default: 40000
    # Maps to: gs_config.cameras.kCamera1StillShutterTimeuS
    still_shutter_us: 40000
  
  # Camera 2 settings
  camera2:
    # Comparison gain
    # Range: 0.1-10.0
    # Default: 0.8
    # Maps to: gs_config.cameras.kCamera2ComparisonGain
    comparison_gain: 0.8
    
    # Calibration/location gain
    # Range: 0.5-10.0
    # Default: 1.0
    # Maps to: gs_config.cameras.kCamera2CalibrateOrLocationGain
    calibrate_gain: 1.0
    
    # Contrast
    # Range: 0.0-32.0
    # Default: 1.2
    # Maps to: gs_config.cameras.kCamera2Contrast
    contrast: 1.2
    
    # Putting mode gain
    # Range: 0.5-10.0
    # Default: 1.5
    # Maps to: gs_config.cameras.kCamera2PuttingGain
    putting_gain: 1.5
    
    # Putting mode contrast
    # Range: 0.0-32.0
    # Default: 1.2
    # Maps to: gs_config.cameras.kCamera2PuttingContrast
    putting_contrast: 1.2
    
    # Still image shutter time (microseconds)
    # Range: 100-1000000
    # Default: 15000
    # Maps to: gs_config.cameras.kCamera2StillShutterTimeuS
    still_shutter_us: 15000

# ============================================================================
# STROBE TIMING ADVANCED
# ============================================================================

strobe_timing:
  # Baud rate for pulse generation
  # Options: 9600, 19200, 38400, 57600, 115200, 230400
  # Default: 115200
  # Maps to: gs_config.strobing.kBaudRateForFastPulses
  baud_rate: 115200
  
  # Putting strobe delay (milliseconds)
  # Range: 0-1000
  # Default: 50
  # Maps to: gs_config.strobing.kPuttingStrobeDelayMs
  putting_delay_ms: 50
  
  # Camera 2 setup period (milliseconds)
  # Range: 500-10000
  # Default: 2000
  # Maps to: gs_config.strobing.kCam2SetupPeriodMilliseconds
  cam2_setup_ms: 2000
  
  # Number of priming pulses
  # Range: 5-50
  # Default: 12
  # Maps to: gs_config.strobing.kNumberPrimingPulses
  priming_pulses: 12
  
  # Priming pulse FPS
  # Range: 5-60
  # Default: 15
  # Maps to: gs_config.strobing.kPrimingPulseFPS
  priming_fps: 15