# PiTrac Basic Configuration
# This file contains the most commonly adjusted settings for PiTrac.
# Edit these values using: pitrac config edit --basic
# 
# For advanced settings, use: pitrac config edit --advanced
# For all settings documentation, see: /etc/pitrac/config/README.md

version: 2.0
profile: basic

# ============================================================================
# SYSTEM SETTINGS
# ============================================================================

system:
  # Camera setup mode
  # Options: single, dual
  # Default: single
  # Note: Dual mode requires two Raspberry Pis networked together
  mode: single
  
  # Camera role (only for dual mode)
  # Options: camera1, camera2
  # Default: camera1
  camera_role: camera1
  
  # Golfer orientation
  # Options: right_handed, left_handed
  # Default: right_handed
  # Note: This affects ball detection zones and trajectory calculations
  golfer_orientation: right_handed
  
  # Start in putting mode
  # Options: true, false
  # Default: false
  # Note: Putting mode uses different strobe timing and detection parameters
  # Maps to: gs_config.modes.kStartInPuttingMode
  putting_mode: false

# ============================================================================
# CAMERA HARDWARE
# ============================================================================

cameras:
  # Camera slot 1 type
  # Options: 1 (PiCam1.3), 2 (PiCam2), 3 (PiHQ), 4 (PiGS), 5 (InnoMaker)
  # Default: 4
  # Maps to: PITRAC_SLOT1_CAMERA_TYPE environment variable
  slot1_type: 4
  
  # Camera slot 2 type
  # Options: 1 (PiCam1.3), 2 (PiCam2), 3 (PiHQ), 4 (PiGS), 5 (InnoMaker)
  # Default: 4
  # Maps to: PITRAC_SLOT2_CAMERA_TYPE environment variable
  slot2_type: 4
  
  # Camera 1 gain
  # Range: 0.5-16.0
  # Default: 1.0
  # Note: Higher values = brighter but more noise
  # Maps to: gs_config.cameras.kCamera1Gain
  camera1_gain: 1.0
  
  # Camera 2 gain
  # Range: 0.5-16.0
  # Default: 4.0
  # Maps to: gs_config.cameras.kCamera2Gain
  camera2_gain: 4.0

# ============================================================================
# SIMULATOR INTEGRATION
# ============================================================================

simulators:
  # E6 Connect host address
  # Format: IP address (empty = disabled)
  # Default: ""
  # Example: "192.168.1.100"
  # Maps to: gs_config.golf_simulator_interfaces.E6.kE6ConnectAddress
  e6_host: ""
  
  # E6 Connect port
  # Range: 1024-65535
  # Default: 2483
  # Maps to: gs_config.golf_simulator_interfaces.E6.kE6ConnectPort
  e6_port: 2483
  
  # GSPro host address
  # Format: IP address (empty = disabled)
  # Default: ""
  # Example: "10.0.0.47"
  # Maps to: gs_config.golf_simulator_interfaces.GSPro.kGSProConnectAddress
  gspro_host: ""
  
  # GSPro port
  # Range: 1024-65535
  # Default: 49152
  # Maps to: gs_config.golf_simulator_interfaces.GSPro.kGSProConnectPort
  gspro_port: 49152

# ============================================================================
# BALL DETECTION
# ============================================================================

ball_detection:
  # Detection method
  # Options: legacy, experimental, experimental_sahi
  # Default: legacy
  # - legacy: HoughCircles detection (most stable)
  # - experimental: YOLO neural network (faster)
  # - experimental_sahi: YOLO with SAHI slicing (best for small balls)
  # Maps to: gs_config.ball_identification.kDetectionMethod
  method: legacy
  
  # Use CLAHE processing (improves contrast)
  # Options: true, false
  # Default: true
  # Maps to: gs_config.ball_identification.kUseCLAHEProcessing
  use_clahe: true
  
  # CLAHE clip limit (contrast enhancement strength)
  # Range: 1-40
  # Default: 8
  # Note: Higher = more contrast enhancement
  # Maps to: gs_config.ball_identification.kCLAHEClipLimit
  clahe_clip_limit: 8
  
  # Expected ball radius at 40cm
  # Range: 50-200 pixels
  # Default: 87
  # Note: Critical for distance calculations
  # Maps to: gs_config.ball_position.kExpectedBallRadiusPixelsAt40cm
  ball_radius_pixels: 87

# ============================================================================
# STROBING (LED TIMING)
# ============================================================================

strobing:
  # Standard ball speed adjustment
  # Range: 0.0 to 10.0 percent
  # Default: 0.1
  # Note: Compensates for ball speed measurement
  # Maps to: gs_config.strobing.kStandardBallSpeedSlowdownPercentage
  standard_speed_adjustment: 0.1
  
  # Practice ball speed adjustment
  # Range: 0.0 to 20.0 percent
  # Default: 4.0
  # Note: Practice balls typically measure slower
  # Maps to: gs_config.strobing.kPracticeBallSpeedSlowdownPercentage
  practice_speed_adjustment: 4.0
  
  # Putting ball speed adjustment
  # Range: 0.0 to 20.0 percent
  # Default: 5.2
  # Maps to: gs_config.strobing.kPuttingBallSpeedSlowdownPercentage
  putting_speed_adjustment: 5.2

# ============================================================================
# DATA STORAGE
# ============================================================================

storage:
  # Log intermediate exposure images
  # Options: true, false
  # Default: true
  # Maps to: gs_config.logging.kLogIntermediateExposureImagesToFile
  log_exposure_images: true
  
  # Log spin analysis images
  # Options: true, false
  # Default: true
  # Maps to: gs_config.logging.kLogIntermediateSpinImagesToFile
  log_spin_images: true
  
  # Log web server images
  # Options: true, false
  # Default: true
  # Maps to: gs_config.logging.kLogWebserverImagesToFile
  log_webserver_images: true
  
  # Use unique filenames for diagnostics
  # Options: true, false
  # Default: true
  # Note: false will overwrite files
  # Maps to: gs_config.logging.kLogDiagnosticImagesToUniqueFiles
  unique_diagnostic_files: true
  
  # Image logging directory
  # Default: ~/LM_Shares/Images/
  # Maps to: gs_config.logging.kLinuxBaseImageLoggingDir
  image_dir: "~/LM_Shares/Images/"
  
  # Web share directory
  # Default: ~/LM_Shares/WebShare/
  # Maps to: gs_config.user_interface.kWebServerShareDirectory
  web_share_dir: "~/LM_Shares/WebShare/"

# ============================================================================
# NETWORK SETTINGS
# ============================================================================

network:
  # ActiveMQ broker address (for dual camera mode)
  # Format: tcp://hostname:port or PITRAC_MSG_BROKER_FULL_ADDRESS
  # Default: tcp://localhost:61616
  # Maps to: gs_config.ipc_interface.kWebActiveMQHostAddress
  broker_address: "tcp://localhost:61616"
  
  # Web interface refresh interval
  # Range: 1-60 seconds
  # Default: 3
  # Maps to: gs_config.user_interface.kRefreshTimeSeconds
  web_refresh_seconds: 3

# ============================================================================
# SPIN CALCULATION
# ============================================================================

spin:
  # Skip spin calculation
  # Options: true, false
  # Default: false
  # Note: Set to true for putting-only or debugging
  # Maps to: gs_config.golf_simulator_interfaces.kSkipSpinCalculation
  skip_calculation: false
  
  # Write spin analysis CSV files
  # Options: true, false
  # Default: true
  # Maps to: gs_config.spin_analysis.kWriteSpinAnalysisCsvFiles
  write_csv_files: true