# Bashly Settings
# This file configures how Bashly generates the script

# Source directory containing command implementations
source_dir: src

# Library directory containing shared functions
# These will be embedded into the generated script
lib_dir: lib

# Commands directory (relative to source_dir)
# Leave empty to use source_dir directly
commands_dir: .

# Partials extension
partials_extension: sh

# Target directory for the generated script
target_dir: .

# Set production mode for cleaner output
env: production

# Strict mode - exit on any error
strict: true

# Enable bash3 compatibility check
bash3_bouncer: true

# Tab stops for indentation
tab_indent: 2

# Generate a standalone script
# This ensures all dependencies are embedded
dependencies: embedded