---
name: "CLA Assistant"

on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, synchronize, reopened, closed]

permissions:
  contents: read
  pull-requests: write
  statuses: write

concurrency:
  group: cla-assistant-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  cla-assistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: >
          github.event_name == 'pull_request_target' ||
          github.event.comment.body == 'recheck' ||
          github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA'
        uses: contributor-assistant/github-action@2.6.1
        env:
          # Built-in token for commenting on the PR and setting statuses in PiTrac
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Fine-grained / classic PAT that can write to PitracCLASignatures
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          path-to-document: "https://gist.github.com/jamespilgrim/e6996a438adc0919ebbe70561efbb600#file-verdant-contributor-license-agreement-md"
          path-to-signatures: "signatures/version1/cla.json"

          remote-organization-name: "jamespilgrim"
          remote-repository-name: "PitracCLASignatures"

          branch: "main"

          allowlist: "dependabot[bot],github-actions[bot]"

          # lock-pullrequest-aftermerge: true
          # suggest-recheck: true

